# Number of days of inactivity before an issue becomes stale
daysUntilStale: 84
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - greenkeeper
  - bug
  - security
  - enhancement
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
  Apologies if the issue could not be resolved. FeathersJS ecosystem
  modules are community maintained so there may be a chance that there isn't anybody
  available to address the issue at the moment.
  For other ways to get help [see here](https://docs.feathersjs.com/help/readme.html).
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
# Only close stale issues
only: issues
